### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/home/arthur/local/ludobox-ui/data'

### ISSUE THREAD

**Issue by arthurlutz** [ludobox/ludobox#1]
Traceback on missing data directory. 

```
$ python ludocore.py generate
Create games directory: SUCCESS
Traceback (most recent call last):
  File "ludocore.py", line 1167, in <module>
    main()
  File "ludocore.py", line 1163, in main
    return args.func(**vars(args))  # We use `vars` to convert args to a dict
  File "ludocore.py", line 750, in generate_all
    for path in sorted(os.listdir(input_dir)):
OSError: [Errno 2] No such file or directory: '/home/arthur/local/ludobox-ui/data'
```

I don't think I missed a step in the README but if I did, it would be nicer to have an error message instead of a traceback.

**Comment by arthurlutz** [comment]
```mkdir data``` solves the problem obviously.

**Comment by clemsos** [comment]
Yep, and you need at least a game to generate the index :)
here is a basic doc 5b208650e3f2b995715fbb5b269c74a67621b7c0
