### ISSUE TITLE
Fail on fresh install

### ISSUE THREAD

**Issue by clemsos** [ludobox/ludobox#2]
On Debian jessie after ```git clone && python setup.py install```

```
(venv)╭─clemsos@miner  ~/Dev/ludobox/ludobox-ui ‹ruby-2.2.1› ‹master› 
╰─$ ludobox generate
Traceback (most recent call last):
  File "/home/clemsos/Dev/ludobox/ludobox-ui/venv/bin/ludobox", line 9, in <module>
    load_entry_point('ludobox==0.0.1', 'console_scripts', 'ludobox')()
  File "/home/clemsos/Dev/ludobox/ludobox-ui/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/clemsos/Dev/ludobox/ludobox-ui/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/home/clemsos/Dev/ludobox/ludobox-ui/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named ludocore

**Comment by clemsos** [comment]
```python ludocore.py generate``` reproduces #1
