### ISSUE TITLE
Weird Error at first connection

### ISSUE THREAD

**Issue by clemsos** [ludobox/ludobox#50]
192.168.1.3 - - [02/May/2017 12:21:53] "GET /socket.io/?EIO=3&transport=polling&t=Ll96th9&sid=8aa32ec1b6e1463ebf1242b1754d0c0d HTTP/1.1" 200 -
/home/pi/venv/local/lib/python2.7/site-packages/Werkzeug-0.12.1-py2.7.egg/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
  BrokenFilesystemWarning)
192.168.1.3 - - [02/May/2017 12:21:57] "GET /socket.io/?EIO=3&transport=polling&t=Ll96mJu&sid=25358f298a4d4f93bf03d6a36d1bf0ed HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/pi/venv/lib/python2.7/site-packages/Werkzeug-0.12.1-py2.7.egg/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/pi/venv/lib/python2.7/site-packages/Werkzeug-0.12.1-py2.7.egg/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/home/pi/venv/lib/python2.7/site-packages/Flask-0.12.1-py2.7.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/venv/lib/python2.7/site-packages/Flask_SocketIO-2.8.6-py2.7.egg/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/pi/venv/lib/python2.7/site-packages/python_engineio-1.4.0-py2.7.egg/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/pi/venv/lib/python2.7/site-packages/python_socketio-1.7.4-py2.7.egg/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/pi/venv/lib/python2.7/site-packages/python_engineio-1.4.0-py2.7.egg/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/home/pi/venv/lib/python2.7/site-packages/python_engineio-1.4.0-py2.7.egg/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/home/pi/venv/lib/python2.7/site-packages/python_engineio-1.4.0-py2.7.egg/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
192.168.1.21 - - [02/May/2017 12:22:06] "GET / HTTP/1.1" 200 -
192.168.1.21 - - [02/May/2017 12:22:08] "GET /css/normalize.css HTTP/1.1" 200 -
192.168.1.21 - - [02/May/2017 12:22:08] "GET /css/skeleton.css HTTP/1.1" 200 -
192.168.1.21 - - [02/May/2017 12:22:08] "GET /css/style.css HTTP/1.1" 200 -
192.168.1.21 - - [02/May/2017 12:22:08] "GET /css/icono.min.css HTTP/1.1" 200 -
192.168.1.21 - - [02/May/2017 12:22:08] "GET /js/bundle.js HTTP/1.1" 200 -
192.168.1.21 - - [02/May/2017 12:22:08] "GET /css/toastr.css HTTP/1.1" 200 -
192.168.1.3 - - [02/May/2017 12:22:12] "GET /games HTTP/1.1" 200 -
socket io connected

**Comment by clemsos** [comment]
Still happening 
```
socket io connected
socket io connected
soTraceback (most recent call last):
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 909, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Mon May 22 13:57:37 2017 {'REMOTE_PORT': '44727', 'HTTP_HOST': 'box.ludobox.net,box.ludobox.net', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 26)} failed with KeyError

Traceback (most recent call last):
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 909, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/home/ludobox/venv/local/lib/python2.7/site-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Mon May 22 13:58:38 2017 {'REMOTE_PORT': '44731', 'HTTP_HOST': 'box.ludobox.net,box.ludobox.net', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 26)} failed with KeyError
```
